//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyoneDegrees.Common {

class CommonPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="SWIGRegisterExceptionCallbacks_Common")]
    public static extern void SWIGRegisterExceptionCallbacks_Common(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_Common")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_Common(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_Common(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_Common(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="SWIGRegisterStringCallback_Common")]
    public static extern void SWIGRegisterStringCallback_Common(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_Common(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static CommonPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_MapStringStringSwig__SWIG_0___")]
  public static extern global::System.IntPtr new_MapStringStringSwig__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_MapStringStringSwig__SWIG_1___")]
  public static extern global::System.IntPtr new_MapStringStringSwig__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_size___")]
  public static extern uint MapStringStringSwig_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_empty___")]
  public static extern bool MapStringStringSwig_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_Clear___")]
  public static extern void MapStringStringSwig_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_getitem___")]
  public static extern string MapStringStringSwig_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_setitem___")]
  public static extern void MapStringStringSwig_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_ContainsKey___")]
  public static extern bool MapStringStringSwig_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_Add___")]
  public static extern void MapStringStringSwig_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_Remove___")]
  public static extern bool MapStringStringSwig_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_create_iterator_begin___")]
  public static extern global::System.IntPtr MapStringStringSwig_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_get_next_key___")]
  public static extern string MapStringStringSwig_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_MapStringStringSwig_destroy_iterator___")]
  public static extern void MapStringStringSwig_destroy_iterator(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_delete_MapStringStringSwig___")]
  public static extern void delete_MapStringStringSwig(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_VectorStringSwig__SWIG_0___")]
  public static extern global::System.IntPtr new_VectorStringSwig__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_VectorStringSwig__SWIG_1___")]
  public static extern global::System.IntPtr new_VectorStringSwig__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Clear___")]
  public static extern void VectorStringSwig_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Add___")]
  public static extern void VectorStringSwig_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_size___")]
  public static extern uint VectorStringSwig_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_empty___")]
  public static extern bool VectorStringSwig_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_capacity___")]
  public static extern uint VectorStringSwig_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_reserve___")]
  public static extern void VectorStringSwig_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_VectorStringSwig__SWIG_2___")]
  public static extern global::System.IntPtr new_VectorStringSwig__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_getitemcopy___")]
  public static extern string VectorStringSwig_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_getitem___")]
  public static extern string VectorStringSwig_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_setitem___")]
  public static extern void VectorStringSwig_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_AddRange___")]
  public static extern void VectorStringSwig_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_GetRange___")]
  public static extern global::System.IntPtr VectorStringSwig_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Insert___")]
  public static extern void VectorStringSwig_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_InsertRange___")]
  public static extern void VectorStringSwig_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_RemoveAt___")]
  public static extern void VectorStringSwig_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_RemoveRange___")]
  public static extern void VectorStringSwig_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Repeat___")]
  public static extern global::System.IntPtr VectorStringSwig_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Reverse__SWIG_0___")]
  public static extern void VectorStringSwig_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Reverse__SWIG_1___")]
  public static extern void VectorStringSwig_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_SetRange___")]
  public static extern void VectorStringSwig_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Contains___")]
  public static extern bool VectorStringSwig_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_IndexOf___")]
  public static extern int VectorStringSwig_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_LastIndexOf___")]
  public static extern int VectorStringSwig_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_VectorStringSwig_Remove___")]
  public static extern bool VectorStringSwig_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_delete_VectorStringSwig___")]
  public static extern void delete_VectorStringSwig(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_Transform__SWIG_0___")]
  public static extern global::System.IntPtr new_Transform__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_new_Transform__SWIG_1___")]
  public static extern global::System.IntPtr new_Transform__SWIG_1(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_Transform_fromJsonGHEV___")]
  public static extern global::System.IntPtr Transform_fromJsonGHEV(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_Transform_fromBase64GHEV___")]
  public static extern global::System.IntPtr Transform_fromBase64GHEV(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_Transform_fromSUA___")]
  public static extern global::System.IntPtr Transform_fromSUA(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("FiftyoneDegrees.Common.Native.dll", EntryPoint="CSharp_FiftyoneDegreesfCommon_delete_Transform___")]
  public static extern void delete_Transform(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
