name: Nightly Pipeline

on:
  workflow_dispatch:
    inputs:
      dryrun:
        required: false
        type: boolean
        default: false
  # schedule:
  #   - cron: '5 0 * * *'

jobs:
  nightly_pipeline:
    uses: postindustria-tech/common-ci/.github/workflows/nightly-pipeline.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

